### ISSUE TITLE
5.5 shallow copy

### ISSUE THREAD

**Issue by michaelqizhi** [jtr13/d3book#11]
Here's the code: 
var x = [12, 34, 1, 43, 90, 72];      // try me
var y = x;
d3.quantile(y.sort(d3.ascending), .25);

I think line 2 should be var y=x.slice(); as is in 5.4.

**Comment by jtr13** [comment]
Thank you! Upon further reflection, I've decided to just mention that `.sort()` modifies the original array and put the issue of deep copies in a footnote. While `.slice()` works in this context to deep copy, it is not technically a deep copy method. The issue of shallow vs. deep copies in JavaScript is actually quite involved, and I don't want it to be a distraction from our focus on D3. (If you come across other topics that weren't covered in class or seem tangential to our main goals, please let me know.)
