### ISSUE TITLE
pdf / epub

### ISSUE THREAD

**Issue by shaggycamel** [jtr13/d3book#24]
Hey Team, when clicking the pdf icon a 404 file not found error is thrown.

Also, it would be really cool if this could be downloaded as ePub so it can be read on eReaders.

Thanks,
Oli

![Screenshot_2021-02-18-21-58-31-61](https://user-images.githubusercontent.com/30674501/108347639-dc034600-7234-11eb-9985-a31f6ab28eb6.jpg)

**Comment by jtr13** [comment]
Thanks for the feedback! I've been making the resource more interactive so I'm not sure how useful the pdf/epub version would be but I'll look into at least updating the pdf and fixing the link when I get a chance.

**Comment by jtr13** [comment]
The download link has been removed.
